(source gnu)
(source melpa)
(source marmalade)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
;;コーディングルールチェッを走らせる
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
;;GitをEmacsから使うインターフェースを提供する
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")

;検索の拡張
(depends-on "anzu")

;カーソルの乗っているシンボルや，指定したシンボルをハイライトしてくれる
(depends-on "highlight-symbol")

;カラーテーマ
;tango
;;(depends-on "color-theme-tango")
;;solarized
(depends-on "color-theme-solarized")

;;対応するかっこに色付け
(depends-on "rainbow-delimiters")

;;自動補完
(depends-on "auto-complete")
(depends-on "ac-dabbrev")

(depends-on "init-loader)
